#!/bin/sh

NODEARCH=`uname -m`
OLDPATH=$PATH
WHEREAMI=`pwd`

DARWIN_FLAG=`uname -a | grep "Darwin"`

if [ ! -d "$WHEREAMI/nodejs-runtime" ]; then
  git clone https://github.com/internetofcoins/nodejs-runtime
fi

if [ ! -d "$WHEREAMI/nodejs-runtime/darwin-x64" ]; then
  cd nodejs-runtime
  git pull origin master
  cd ..
fi

if [ ! -L "$WHEREAMI/node" ]; then
  ln -s "./nodejs-runtime/$NODEARCH" "$WHEREAMI/node"
fi

if [ "$DARWIN_FLAG" != "" ]; then
 # fix node for eat Apple
 rm ./node
 ln -s "./nodejs-runtime/darwin-x64" "$WHEREAMI/node"
fi


export PATH=$WHEREAMI/node/bin:"$PATH"
NODEINST=`which node`

cd views
./compileviews.sh
cd ..

cd lib
if [ -z "$@" ]; then
	echo
	echo "Starting hybridd..."
	echo " [i] using node executable $NODEINST"
	node hybridd.js
	echo
	echo "Stopped hybridd."
	echo
else
	node hcmd.js $@
fi

PATH=$OLDPATH
