#!/bin/sh
#
#   ******************************************************************************
#   * hybridd bash script -> launch hybridd or issue a command line function     *
#   * Copyright © 2016-2017 Joachim de Koning, Amadeus de Koning                 *
#   *                                                                            *
#   * This work is licensed under the GPLv3. See the LICENSE files at            *
#   * the top-level directory of this distribution for the individual copyright  *
#   * holder information and the developer policies on copyright and licensing.  *
#   *                                                                            *
#   * Unless otherwise agreed in a custom licensing agreement, no part of the    *
#   * this software, including this file, may be copied, modified, propagated,   *
#   * or distributed except according to the terms contained in the LICENSE      *
#   * file.                                                                      *
#   *                                                                            *
#   * Removal or modification of this copyright notice is prohibited.            *
#   *                                                                            *
#   ******************************************************************************
#

#!/bin/sh
OLDPATH=$PATH
WHEREAMI=`pwd`
export PATH=$WHEREAMI/node/bin:"$PATH"
NODEINST=`which node`

cd lib
if [ -z "$@" ]; then
	echo
	echo "Starting hybridd..."
	echo " [i] using node executable $NODEINST"
	node hybridd.js
	# EXPERIMENTAL: node ../node_modules/run/run.js hybridd.js
	echo
	echo "Stopped hybridd."
	echo
else
	node hcmd.js $@
fi

PATH=$OLDPATH
